In [2]:
import numpy as np

np.random.seed(10)

A = np.random.randint(0, 9, 12).reshape(4,3)
b = np.random.randint(0, 9, 3).reshape(3,1)

In [3]:
A

array([[4, 0, 1],
       [0, 1, 8],
       [0, 8, 6],
       [4, 3, 0]])

In [4]:
b

array([[4],
       [6],
       [8]])

In [5]:
C = np.dot(A,b)

C

array([[24],
       [70],
       [96],
       [34]])

In [6]:
C_ = np.array([A[:,[i]]*b[i] for i in range(A.shape[1])])
print(C_.shape)
C_.sum(axis=0)

(3, 4, 1)


array([[24],
       [70],
       [96],
       [34]])

In [7]:
B = np.random.randint(0, 9, 6).reshape(3,2)

In [8]:
B

array([[1, 8],
       [4, 1],
       [3, 6]])

In [9]:
C = np.dot(A,B)

C

array([[ 7, 38],
       [28, 49],
       [50, 44],
       [16, 35]])

In [10]:
C_ = np.array([ [A[:,[i]]*B[i,j] for i in range(A.shape[1]) ] for j in range(B.shape[1]) ])

print(C_.shape)
C_ = C_.transpose(1, 2, 0, 3)
print(C_.shape)
C_ = C_.sum(axis=0)
print(C_.shape)
C_.squeeze()

(2, 3, 4, 1)
(3, 4, 2, 1)
(4, 2, 1)


array([[ 7, 38],
       [28, 49],
       [50, 44],
       [16, 35]])

In [11]:
A = np.eye(5)*np.array([1,3,0,5,4])

In [12]:
A

array([[1., 0., 0., 0., 0.],
       [0., 3., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 4.]])

In [13]:
A = np.random.randint(0,10,12).reshape(4,3) #-----[1]
x = np.random.randint(0,10,3)


print(A)
print(x)

[[5 3 9]
 [6 9 1]
 [9 4 2]
 [6 7 8]]
[8 9 2]


In [14]:
m = x.shape[0] #-----[2]
y = [] #-----[3]
temp = 0
for i in range(A.shape[0]) : #-----[4]
    for j in range(m) : #-----[5]
        temp += A[i,j]*x[j] #-----[6]
    y.append(temp) #-----[7]
    temp = 0

In [15]:
y

[85, 131, 112, 127]

In [16]:
A.dot(x)

array([ 85, 131, 112, 127])

In [17]:
A@x

array([ 85, 131, 112, 127])

In [18]:
A = np.random.randint(0,10,12).reshape(3,4) 
x = np.random.randint(0,10,3)

In [19]:
m = x.shape[0] 
y = [] 
temp = 0
for i in range(A.shape[1]) : 
    for j in range(m) : 
        temp += A[j,i]*x[j] #-----[1]
    y.append(temp) 
    temp = 0

In [20]:
y

[8, 162, 97, 120]

In [21]:
y = A.T.dot(x) 
y

array([  8, 162,  97, 120])

In [22]:
A.T@x

array([  8, 162,  97, 120])

In [23]:
np.random.seed(10)

n, m = 5, 2

X = np.random.rand(n, m)
w = np.random.rand(m)
y = np.random.rand(n)

In [24]:
X

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [25]:
w

array([0.68535982, 0.95339335])

In [26]:
y

array([0.00394827, 0.51219226, 0.81262096, 0.61252607, 0.72175532])

In [27]:
g = np.zeros_like(w)

# X:(5,2), y:(5,), w:(2,)
for j in range(m):
    for i in range(n):
        g[j] += (np.dot(X[i,:], w) - y[i]) * X[i,j]

In [28]:
g

array([0.65598053, 0.57259869])

In [29]:
g = np.dot(X.T, np.dot(X,w)-y)
g

array([0.65598053, 0.57259869])